### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by liliangqi** [ZHHJemotion/Infant-Face-Verification#1]
Hi, I'd like to verify two faces by comparing there representations in embedding space. How can I detect and extract features from a face image using your code?

**Comment by ZHHJemotion** [comment]
Hi, 
My code cannot detect face. I did face pre-processing when I prepareed the face dataset. For extracting face features, the deepid2.py containing 4 conv layers is applied to extract one face. The siamese net, Siamese_net.py, has two branches. If you want to detect face by deep learning, you can reference [https://github.com/kpzhang93/MTCNN_face_detection_alignment](url), or by other method, I think [http://dlib.net/](url) is a good choice.

**Comment by liliangqi** [comment]
Thank you very much!
